#!/usr/bin/env python

# This file is part of ctrl_bps.
#
# Developed for the LSST Data Management System.
# This product includes software developed by the LSST Project
# (https://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
import os
import sys

from lsst.utils import doImport

if __name__ == "__main__":
    # Check for env vars before importing code because the LSST click
    # code hides that the problem is missing environment variables required
    # during imports of third-party modules.
    for key in [
        "PANDA_AUTH",
        "PANDA_VERIFY_HOST",
        "PANDA_AUTH_VO",
        "PANDA_URL_SSL",
        "PANDA_URL",
        "IDDS_CONFIG",
    ]:
        if key not in os.environ:
            raise OSError(f"Missing environment variable {key}")

    panda_auth_mod = doImport("lsst.ctrl.bps.wms.panda.cli.panda_auth")
    sys.exit(panda_auth_mod.main())
